version: '3'
services:
  backend:
    container_name: backend
    image: snoony/starlight-be
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=172.17.0.1
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - network
  frontend:
    container_name : frontend
    image: snoony/starlight-fe
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - network